baseURL = "https://example.org/"
languageCode = "id-id"
title = "Test Hugo"
[params]
    ShowReadingTime = true

[params.profileMode]
    enabled = true
    title = "Toraja Digital Gallery"
    subtitle = "Menjaga Tradisi, Melintasi Zaman."
