baseURL = "https://toraja-digital-gallery.pages.dev/"
languageCode = "id-id"
title = "Test Hugo"

[params]
    ShowReadingTime = true

[params.profileMode]
    enabled = true
    title = "Toraja Digital Gallery"
    subtitle = "Menjaga Tradisi, Melintasi Zaman."

[taxonomies]
  kategori = "kategori"

[permalinks]
  kategori = "/galeri/kategori/:slug/"

[sitemap]
  changefreq = "weekly"
  priority = 0.5